src/Entity/Picture.php
<?php

namespace App\Entity;

use App\Repository\PictureRepository;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass=PictureRepository::class)
 */
class Picture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="photos", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        if ($imageFile !== null) {
            $this->updated_at = new \DateTimeImmutable();
        }
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    public function setIsValidated(bool $is_validated): self
    {
        $this->is_validated = $is_validated;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Picture;
use App\Entity\Category;
use Symfony\Component\HttpFoundation\Request;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        // équivalent à un SELECT * FROM pictures
        $resultsPictures = $this->getDoctrine()->getRepository(Picture::class)->findBy(['is_validated' => true]);
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        // page par page
        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            $resultsPictures, // Requête contenant les données à paginer (ici nos articles)
            $page === 0 ? 1 : $page,
            12 // Nombre de résultats par page
        );

        return $this->render('home/index.html.twig', [
            'pictures' => $pictures,
            'categories' => $categories
            ]);
    }

    /**
     * @Route("/category/{id}", name="pictures_by_category")
     */
    public function picturesByCategory($id, PaginatorInterface $paginator, Request $request)
    {
        // dd($id);
        // dump($id);
        $category = $this->getDoctrine()->getRepository(Category::class)->find($id);
        $query = $this->getDoctrine()->getRepository(Picture::class)->findBy([
            'category' => $category,
            'is_validated' => true
        ]);

        if(!$category){
            // Si aucun article n'est trouvé, nous créons une exception
            throw $this->createNotFoundException('La catégorie n\'existe pas');
        }

        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            $category->getPictures(), // Requête contenant les données à paginer (ici nos articles)
            $page === 0 ? 1 : $page,
            6 // Nombre de résultats par page
        );

        // Si l'article existe nous envoyons les données à la vue
        return $this->render('home/picturesByCategory.html.twig', [
            'category' => $category,
            'pictures' => $pictures
            ]);
    }

    /**
     * @Route("/show/picture/{id}", name="show_picture", requirements={"id"="\d+"})
     */
    public function showPicture($id, PaginatorInterface $paginator, Request $request)
    {
        $picture = $this->getDoctrine()->getRepository(Picture::class)->find($id);
        $pictures = $this->getDoctrine()->getRepository(Picture::class)->findBy([
            'category' => $picture->getCategory(),
            'is_validated' => true
        ]);

        if(!$picture){
            // Si aucun article n'est trouvé, nous créons une exception
            throw $this->createNotFoundException('L\'image n\'existe pas');
        }

        $page = $request->query->getInt('page', 1);
        $photos = $paginator->paginate(
            $pictures, // Requête contenant les données à paginer (ici nos articles)
            $page === 0 ? 1 : $page,
            3 // Nombre de résultats par page
        );
        
        return $this->render('home/showPicture.html.twig',[
            'picture' => $picture,
            'photos' => $photos

        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block body %}
	<h1>Home</h1>
	<ul class="nav justify-content-center py-4">
		{% for category in categories %}
			<li class="nav-item">
				<a class="nav-link" href="{{ path('pictures_by_category', { id: category.id }) }}">{{ category.name  }}</a>
			</li>
		{% endfor %}
	</ul>
	<div class="justify-content-center py-4">
		<div class="row">
			{% for picture in pictures %}
				<div class="col-4">
					<a href="{{ path('show_picture', { id: picture.id }) }}">
						<img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}">
					</a>
				</div>
			{% endfor %}
			{{ knp_pagination_render(pictures) }}
		</div>
	</div>
{% endblock %}

templates/home/picturesByCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Images de la catégorie:
	{{ category.name  }}
{% endblock %}

{% block body %}

	<h1>Catégorie "{{ category.name  }}"</h1>

	<div class="row">
		{% for picture in pictures %}
			<div class="col-3 mb-4">
				<a href="{{ path('show_picture', { id: picture.id }) }}">
					<img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}" class="rounded img-fluid">
				</a>
			</div>
		{% endfor %}
		{{ knp_pagination_render(pictures) }}
	</div>

{% endblock %}

templates/home/showPicture.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Apperçu de la photo
{% endblock %}

{% block body %}

	<h1>Apperçu de la photo</h1>

	<div class="py-4">
		<a href="{{ path('home') }}">Retour à la page d'Accueil</a>
	</div>

	<a href="{{ asset('uploads/images/photos/'~ picture.image) }}">
		<img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('medium') }}" alt="{{ picture.image }}" class="rounded img-fluid">
	</a>
	<p class="pt-3">{{ picture.description }}</p>
	<p class="text-muted">{{ picture.tags }}</p>
	<p>Photographié le {{ picture.createdAt|date }}</p>
	<div class="row">
		{% for photo in photos %}
			{% if photo.image is not same as(picture.image) %}
				<div class="col-3 mb-4">
					<a href="{{ path('show_picture', { id: photo.id }) }}">
						<img src="{{ asset('uploads/images/photos/'~ photo.image)|imagine_filter('thumbnail') }}" alt="{{ photo.image }}" class="rounded img-fluid">
					</a>
				</div>
			{% endif %}
		{% endfor %}
		{{ knp_pagination_render(photos) }}

	</div>

{% endblock %}